eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/api/v1/payment
  main-service:
    endpoints:
      endpoint:
        uri: http://MAIN-SERVICE/api/v1/main
  security-service:
    endpoints:
      endpoint:
        uri: http://SECURITY-SERVICE/api/v1/auth
  platform-service:
    endpoints:
      endpoint:
        uri: http://PLATFORM-SERVICE/api/v1/movie

app:
  jwtSecret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  jwtExpirationHour: 3600000 #uma hora
  jwtExpirationDay: 86400000 #um dia
  jwtExpirationMonth: 2678400000 #um mes
  jwtExpirationYear: 31104000000 #um ano
