server:
  port: 9193

spring:
  data:
    mongodb:
      user: admin
      pwd: password
      host: localhost
      port: 27017
      database: scs
      authentication-database: admin
  #h2:
  # console:
  #    enabled: true
  #datasource:
  #  url: jdbc:h2:mem:testdb
  #  username: sa
  #  driverClassName: org.h2.Driver
  #  jpa:
  #    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: SECURITY-SERVICE
  config:
    import: "optional:configserver:http://localhost:9196"

logging:
  file:
    path: C:/Users/roger/Desktop/TCC/sgs/logs
    name: C:/Users/roger/Desktop/TCC/sgs/logs/microservice.log

